services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
        - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_REPLACE}
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: always
    networks:
     - my-net
  postgres:
    image: postgres:15.3-alpine3.17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - my-net
      
volumes:
  docker-nest-postgres:
networks:
  my-net:
    driver: bridge